name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      working-directory: ./test/ZooLabApplication.Test
      run: dotnet restore
    - name: Build
      working-directory: ./test/ZooLabApplication.Test
      run: dotnet build --no-restore
    - name: TestCodeCov
      working-directory: ./test/ZooLabApplication.Test
      run: dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutput=TestResults/ 
    - uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
        #working-directory: ./test/CustomerClassLibrary.Test/TestResults/
        files: ./test/ZooLabApplication.Test/TestResults/coverage.opencover.xml
        flags: unittests 
        name: codecov-umbrella
        fail_ci_if_error: true 
        verbose: true
